name: b-controlled-box-foreman
version: '0.1.0'
summary: Foreman ROS 2 Package with ctrlX Data Layer integration
description: Package for managing ros2_control component lifecycle using ctrlX non-RT Data Layer
base: core24
confinement: strict

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

apps:
  foreman-node:
    command: bin/entrypoint.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - datalayer
      - active-solution
    extensions: [ros2-jazzy]

parts:
  ctrlx-datalayer-deb:
    plugin: nil
    source: ./assets/
    override-build: |
      echo "Extracting the ctrlX datalayer .deb package ..."
      # This extracts the .deb into the snap's filesystem
      # It puts python files in /usr/lib/python3/dist-packages/ 
      # and C++ libs in /usr/lib/, which the snap automatically discovers.
      dpkg -x ctrlx-datalayer-3.5.2.deb $SNAPCRAFT_PART_INSTALL

  ctrlx-fbs-wheel:
    after: [ctrlx-datalayer-deb]
    plugin: python
    source: ./assets/
    python-packages:
      - ctrlx_fbs-2.6.0-py3-none-any.whl

  foreman:
    after: [ctrlx-fbs-wheel]
    plugin: colcon
    source: https://github.com/b-robotized/foreman.git
    source-branch: datalayer
    source-type: git
    build-environment:
      - ROS_VERSION: '2'
      - ROS_DISTRO: 'jazzy'
      - PYTHONPATH: "/usr/lib/python3/dist-packages:${PYTHONPATH:-}"
    build-packages:
      - build-essential
      - ros-jazzy-rosidl-default-generators
      - ros-jazzy-ros-environment
    stage-packages:
      - ros-jazzy-rclpy
      - ros-jazzy-ros2run
      - ros-jazzy-ros2launch
      - ros-jazzy-launch-ros
      - ros-jazzy-rmw-zenoh-cpp  

  scripts:
    plugin: dump
    source: .
    organize:
      entrypoint.sh: bin/entrypoint.sh
      foreman.default.env: etc/foreman.default.env

# Ignored because the C++ binaries in the wheel are pre-compiled and might trip the snapcraft linter
lint:
  ignore:
    - library:
        - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
        - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*