from dataclasses import dataclass
from dataclasses import field
from enum import Enum
from typing import Dict, List, Optional

from lifecycle_msgs.msg import State


class ComponentType(Enum):
    HARDWARE = "hardware"
    CONTROLLER = "controller"

class LifecycleState(Enum):
    """
    ROS 2 control component lifecycle sequence.

    Based on ROS lifecycle_msgs.State.
    """

    UNCONFIGURED = State.PRIMARY_STATE_UNCONFIGURED
    INACTIVE = State.PRIMARY_STATE_INACTIVE
    ACTIVE = State.PRIMARY_STATE_ACTIVE
    FINALIZED = State.PRIMARY_STATE_FINALIZED

    @property
    def ros_state(self) -> State:
        """Generate the ROS 2 message object."""
        labels = {
            1: 'unconfigured',
            2: 'inactive',
            3: 'active',
            4: 'finalized'
        }
        return State(id=self.value, label=labels.get(self.value, 'unknown'))

    def step_towards(self, target: 'LifecycleState') -> Optional['LifecycleState']:
        """Calculate 1 step forward or backward in the sequence."""
        if self == target:
            return None

        sequence = list(LifecycleState)
        index_current = sequence.index(self)
        index_target = sequence.index(target)

        if index_current < index_target:
            return sequence[index_current + 1]
        else:
            return sequence[index_current - 1]

@dataclass
class Component:
    """A single hardware interface or a controller we are managing."""

    name: str
    component_type: ComponentType
    lifecycle_state: LifecycleState

@dataclass
class SystemState:
    """Current state of the control system. Populated from ControllerManager::Activity message."""

    components: Dict[str, Component] = field(default_factory=dict)

@dataclass
class ControllerDependencyRule:
    """Defines what hardware must be active before controller is active. Populated from YAML."""

    controller_name: str
    required_hardware: List[str]

@dataclass
class SystemGoal:
    """Named system goal state. Populated from YAML."""

    name: str
    hardware_goals: List[Component] = field(default_factory=list)
    controller_goals: List[Component] = field(default_factory=list)

@dataclass
class SystemTransitionCommand:
    """1-step instruction generated by the planner based on current state to be executed on the ControllerManager."""

    component: Component
    goal_state: LifecycleState

    def __repr__(self):
        return f"TransitionCommand({self.component.component_type.value} '{self.component.name}' -> state_id={self.goal_state.name})"
